version: 2.0

jobs:
  build:
    docker:
      - image: cimg/node:18.12.1
      - image: circleci/postgres:9.5
        name: postgresql
        environment:
          POSTGRES_USER: iroco
          POSTGRES_PASSWORD: iroco
          POSTGRES_DB: test

    steps:
      - checkout
      - attach_workspace:
            at: /tmp/jmap-admin
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@8'

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: install dependencies
          command: npm ci

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          name: eslint
          command: npm run lint

      - run:
          name: build
          command: npm run build

      - run:
          name: make test db
          command: |
            PGPASSWORD=iroco psql -U iroco -h postgresql test < bootstrap_db.sql
            npm run db:test

      - run:
          name: run unit test
          command: npm run test

      - run:
          name: run integration tests
          command: npm run test:integration

      - persist_to_workspace:
          root: /tmp/jmap-admin
          paths:
            - .
# Marc Bouvier
  # m.bouvier.dev@gmail.com
  # marc-bouvier
# https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors
  release:
    docker:
      - image: docker:20.10.22-git
    steps:
      - attach_workspace:
          at: /tmp/jmap-admin
      - setup_remote_docker
      - run:
          name: Login to Docker hub
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Install tonistiigi/binfmt support for additional platforms
          command: |
            docker run --privileged --rm tonistiigi/binfmt --install all
      - run:
          name: Build and push the image for several platform
          command: |
            cd /tmp/jmap-admin
            docker buildx create --use
            docker buildx build -f docker/Dockerfile \
              --platform linux/amd64,linux/arm64 \
              -t iroco/jmapadmin:${CIRCLE_TAG} \
              --push .

workflows:
  version: 2
  build_workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^[0-9.]*/
            branches:
              ignore: /.*/